---
title: Digging into NJOAG Law Enforcement Officer Diversity data - Part I
subtitle: A map of the largest percapita municipal PDs in NJ is a map of the Jersey Shore, plus Hi-Nella
author: Tor
date: '2022-06-25'
slug: digging-into-njoag-law-enforcement-officer-diversity-data-part-i
tags:
  - R
  - NJOAGLEOD
---



<div id="njoag-use-of-force-and-law-enforcement-officer-diversity-data-sets" class="section level2">
<h2>NJOAG Use of Force and Law Enforcement Officer Diversity data sets</h2>
<p>The NJ Office of the Attorney General has started releasing data on police <a href="https://www.njoag.gov/force/">use of force</a> and on <a href="https://www.njoag.gov/policerecruiting/">law enforcement officer diversity</a>, which I have re-packaged as R data packages <a href="https://github.com/tor-gu/njoaguof">NJOAGUOF</a> and <a href="https://github.com/tor-gu/njoagleod">NJOAGLEOD</a>.</p>
<p>I’d like to start digging into this data to see what it shows. I’ll start with the municipal agencies – in particular, agency sizes. <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div id="packages-used-in-this-post" class="section level3">
<h3>Packages used in this post</h3>
In this post, I’ll be using the following packages.
<table class="kable">
<thead>
<tr>
<th style="text-align:left;">
Package
</th>
<th style="text-align:left;">
Title
</th>
<th style="text-align:left;">
Version
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
njoagleod
</td>
<td style="text-align:left;">
NJ OAG Law Enforcement Officer Diversity data package
</td>
<td style="text-align:left;">
1.1.3
</td>
</tr>
<tr>
<td style="text-align:left;">
tidyverse
</td>
<td style="text-align:left;">
Easily Install and Load the ‘Tidyverse’
</td>
<td style="text-align:left;">
1.3.1
</td>
</tr>
<tr>
<td style="text-align:left;">
tidycensus
</td>
<td style="text-align:left;">
Load US Census Boundary and Attribute Data as ‘tidyverse’ and
‘sf’-Ready Data Frames
</td>
<td style="text-align:left;">
1.2.1
</td>
</tr>
<tr>
<td style="text-align:left;">
tigris
</td>
<td style="text-align:left;">
Load Census TIGER/Line Shapefiles
</td>
<td style="text-align:left;">
1.6
</td>
</tr>
<tr>
<td style="text-align:left;">
sf
</td>
<td style="text-align:left;">
Simple Features for R
</td>
<td style="text-align:left;">
1.0-7
</td>
</tr>
<tr>
<td style="text-align:left;">
ggrepel
</td>
<td style="text-align:left;">
Automatically Position Non-Overlapping Text Labels with
‘ggplot2’
</td>
<td style="text-align:left;">
0.9.1
</td>
</tr>
</tbody>
</table>
<p>This is not a tutorial for using these packages, but all the R code used to generate the plots and tables will be included.</p>
<p>Both NJOAG packages mentioned above may be installed from github, though we will only use <code>njoagleod</code> in this post.</p>
<pre class="r"><code>install_github(&quot;tor-gu/njoaguof&quot;)
install_github(&quot;tor-gu/njoagleod&quot;)</code></pre>
</div>
</div>
<div id="municipal-agencies-and-census-data" class="section level2">
<h2>Municipal agencies and census data</h2>
<div id="building-a-population-and-officer_count-table-by-municipality" class="section level3">
<h3>Building a population and officer_count table by municipality</h3>
<p>Let’s start by getting municipal-level census data using the <a href="https://walker-data.com/tidycensus/">tidycensus</a> package. <a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> We will use the <code>municipality</code> table in the <code>njoagleod</code> package for the list of counties. For the moment, we only need the population of each municipality.</p>
<pre class="r"><code>library(tidyverse)
library(tidycensus)
library(njoagleod)
# Get a vector of NJ counties
counties &lt;- municipality %&gt;% pull(county) %&gt;% unique() %&gt;% sort()
# Get the population of each municipality using tidycensus::get_estimates
municipality_pop &lt;- counties %&gt;%
  map_df(
    ~ get_estimates(
      geography = &quot;county subdivision&quot;,
      state = &quot;NJ&quot;,
      county = .,
      year = 2019,
      variables = &quot;POP&quot;
    ) %&gt;%
      separate(
        NAME,
        sep = &quot;, &quot;,
        into = c(&quot;municipality&quot;, &quot;county&quot;, &quot;state&quot;)
      )
  ) %&gt;%
  rename(population=value) %&gt;%
  select(-variable, -state)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-4">Table 1: </span>head(municipality_pop)
</caption>
<thead>
<tr>
<th style="text-align:left;">
municipality
</th>
<th style="text-align:left;">
county
</th>
<th style="text-align:left;">
GEOID
</th>
<th style="text-align:right;">
population
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Buena borough
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400108680
</td>
<td style="text-align:right;">
4284
</td>
</tr>
<tr>
<td style="text-align:left;">
Egg Harbor City city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400120350
</td>
<td style="text-align:right;">
4052
</td>
</tr>
<tr>
<td style="text-align:left;">
Hamilton township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400129280
</td>
<td style="text-align:right;">
25746
</td>
</tr>
<tr>
<td style="text-align:left;">
Mullica township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400149410
</td>
<td style="text-align:right;">
5856
</td>
</tr>
<tr>
<td style="text-align:left;">
Somers Point city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400168430
</td>
<td style="text-align:right;">
10174
</td>
</tr>
<tr>
<td style="text-align:left;">
Absecon city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:left;">
3400100100
</td>
<td style="text-align:right;">
8818
</td>
</tr>
</tbody>
</table>
<p>Now let’s get the officer count for each municipal police department and combine it with the census data. Not every municipality has its own police department, and there may be municipal police departments that are excluded for some reason (for example, because they have not reported their data to the OAG).</p>
<pre class="r"><code># Get the officer count for each agency
officer_count_pop &lt;- officer %&gt;%
  count(agency_county, agency_name, name = &quot;officer_count&quot;) %&gt;%
  left_join(agency,
            by = c(&quot;agency_county&quot;, &quot;agency_name&quot;)) %&gt;%
  filter(!is.na(municipality)) %&gt;%
  left_join(municipality,
            by = c(&quot;agency_county&quot; = &quot;county&quot;, &quot;municipality&quot;)) %&gt;%
  select(GEOID, agency_name, officer_count) %&gt;%
  left_join(municipality_pop, by = &quot;GEOID&quot;)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-6">Table 2: </span>head(officer_count_pop)
</caption>
<thead>
<tr>
<th style="text-align:left;">
GEOID
</th>
<th style="text-align:left;">
agency_name
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:left;">
municipality
</th>
<th style="text-align:left;">
county
</th>
<th style="text-align:right;">
population
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
3400100100
</td>
<td style="text-align:left;">
Absecon City PD
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:left;">
Absecon city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
8818
</td>
</tr>
<tr>
<td style="text-align:left;">
3400102080
</td>
<td style="text-align:left;">
Atlantic City PD
</td>
<td style="text-align:right;">
257
</td>
<td style="text-align:left;">
Atlantic City city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
37743
</td>
</tr>
<tr>
<td style="text-align:left;">
3400107810
</td>
<td style="text-align:left;">
Brigantine PD
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:left;">
Brigantine city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
8650
</td>
</tr>
<tr>
<td style="text-align:left;">
3400120350
</td>
<td style="text-align:left;">
Egg Harbor City PD
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
Egg Harbor City city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
4052
</td>
</tr>
<tr>
<td style="text-align:left;">
3400120290
</td>
<td style="text-align:left;">
Egg Harbor Twp PD
</td>
<td style="text-align:right;">
92
</td>
<td style="text-align:left;">
Egg Harbor township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
42249
</td>
</tr>
<tr>
<td style="text-align:left;">
3400125560
</td>
<td style="text-align:left;">
Galloway Twp PD
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:left;">
Galloway township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
35618
</td>
</tr>
</tbody>
</table>
</div>
<div id="checking-that-the-table-is-representative-of-new-jersey." class="section level3">
<h3>Checking that the table is representative of New Jersey.</h3>
<p>As we mentioned above, our <code>officer_count_pop</code> table will not include a row for every municipality of NJ. Before digging in too far, let’s get a sense of what we are including and what we are missing.</p>
<p>Statewide, the municipal agencies for which we have data cover nearly 93% of the population of New Jersey. In all, there are about 408 residents per municipal police officer in these municipalities.</p>
<pre class="r"><code># We cover nearly 93% of the population of NJ
sum(officer_count_pop$population) / sum(municipality_pop$population)</code></pre>
<pre><code>## [1] 0.9276362</code></pre>
<pre class="r"><code># About 408 residents per municipal police officer
sum(officer_count_pop$population) / sum(officer_count_pop$officer_count)</code></pre>
<pre><code>## [1] 407.9133</code></pre>
<p>At the county level, the coverage varies from from about 58% of the population (Salem county) up to 100% (Hudson and Passaic), and the number of residents per officer ranges from 511 (Somerset) to 196 (Cape May). Note that in Cape May, our data covers only 73% of the population.</p>
<pre class="r"><code># Get the population for each municipality that is &#39;missed&#39; and summarize by
# county
missed_county_pop &lt;- municipality_pop %&gt;%
  anti_join(officer_count_pop, by = &quot;GEOID&quot;) %&gt;%
  group_by(county) %&gt;%
  summarize(missed_population = sum(population))
# Get the total population by county
county_pop &lt;- municipality_pop %&gt;%
  group_by(county) %&gt;%
  summarize(population = sum(population))
# Combine this to get the county-level coverage -- the proportion of the 
# population of each county with a municipal PD for which we have the data
coverage &lt;- county_pop %&gt;%
  left_join(missed_county_pop, by = &quot;county&quot;) %&gt;%
  mutate(missed_population = replace_na(missed_population, 0)) %&gt;%
  mutate(coverage = (population - missed_population) / population) %&gt;%
  select(county, missed_population, coverage)
# Now add the county-level municipal PD officer count
officer_count_pop_by_county &lt;- officer_count_pop %&gt;%
  group_by(county) %&gt;%
  summarize(officer_count = sum(officer_count),
            population = sum(population)) %&gt;%
  mutate(resident_per_officer = population / officer_count) %&gt;%
  left_join(coverage, by = &quot;county&quot;)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-9">Table 3: </span>officer_pop_by_county
</caption>
<thead>
<tr>
<th style="text-align:left;">
county
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:right;">
population
</th>
<th style="text-align:right;">
resident_per_officer
</th>
<th style="text-align:right;">
missed_population
</th>
<th style="text-align:right;">
coverage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
809
</td>
<td style="text-align:right;">
244289
</td>
<td style="text-align:right;">
301.9642
</td>
<td style="text-align:right;">
19381
</td>
<td style="text-align:right;">
0.9264952
</td>
</tr>
<tr>
<td style="text-align:left;">
Bergen County
</td>
<td style="text-align:right;">
2170
</td>
<td style="text-align:right;">
923035
</td>
<td style="text-align:right;">
425.3618
</td>
<td style="text-align:right;">
9167
</td>
<td style="text-align:right;">
0.9901663
</td>
</tr>
<tr>
<td style="text-align:left;">
Burlington County
</td>
<td style="text-align:right;">
842
</td>
<td style="text-align:right;">
406464
</td>
<td style="text-align:right;">
482.7363
</td>
<td style="text-align:right;">
38885
</td>
<td style="text-align:right;">
0.9126865
</td>
</tr>
<tr>
<td style="text-align:left;">
Camden County
</td>
<td style="text-align:right;">
949
</td>
<td style="text-align:right;">
413077
</td>
<td style="text-align:right;">
435.2761
</td>
<td style="text-align:right;">
93394
</td>
<td style="text-align:right;">
0.8155985
</td>
</tr>
<tr>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
341
</td>
<td style="text-align:right;">
66866
</td>
<td style="text-align:right;">
196.0880
</td>
<td style="text-align:right;">
25173
</td>
<td style="text-align:right;">
0.7264964
</td>
</tr>
<tr>
<td style="text-align:left;">
Cumberland County
</td>
<td style="text-align:right;">
286
</td>
<td style="text-align:right;">
110990
</td>
<td style="text-align:right;">
388.0769
</td>
<td style="text-align:right;">
38537
</td>
<td style="text-align:right;">
0.7422740
</td>
</tr>
<tr>
<td style="text-align:left;">
Essex County
</td>
<td style="text-align:right;">
2385
</td>
<td style="text-align:right;">
762478
</td>
<td style="text-align:right;">
319.6973
</td>
<td style="text-align:right;">
36497
</td>
<td style="text-align:right;">
0.9543202
</td>
</tr>
<tr>
<td style="text-align:left;">
Gloucester County
</td>
<td style="text-align:right;">
541
</td>
<td style="text-align:right;">
245192
</td>
<td style="text-align:right;">
453.2200
</td>
<td style="text-align:right;">
46444
</td>
<td style="text-align:right;">
0.8407467
</td>
</tr>
<tr>
<td style="text-align:left;">
Hudson County
</td>
<td style="text-align:right;">
2067
</td>
<td style="text-align:right;">
672391
</td>
<td style="text-align:right;">
325.2980
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Hunterdon County
</td>
<td style="text-align:right;">
204
</td>
<td style="text-align:right;">
94252
</td>
<td style="text-align:right;">
462.0196
</td>
<td style="text-align:right;">
30119
</td>
<td style="text-align:right;">
0.7578294
</td>
</tr>
<tr>
<td style="text-align:left;">
Mercer County
</td>
<td style="text-align:right;">
755
</td>
<td style="text-align:right;">
350981
</td>
<td style="text-align:right;">
464.8755
</td>
<td style="text-align:right;">
16449
</td>
<td style="text-align:right;">
0.9552323
</td>
</tr>
<tr>
<td style="text-align:left;">
Middlesex County
</td>
<td style="text-align:right;">
1524
</td>
<td style="text-align:right;">
757317
</td>
<td style="text-align:right;">
496.9272
</td>
<td style="text-align:right;">
67745
</td>
<td style="text-align:right;">
0.9178910
</td>
</tr>
<tr>
<td style="text-align:left;">
Monmouth County
</td>
<td style="text-align:right;">
1507
</td>
<td style="text-align:right;">
578260
</td>
<td style="text-align:right;">
383.7160
</td>
<td style="text-align:right;">
40535
</td>
<td style="text-align:right;">
0.9344937
</td>
</tr>
<tr>
<td style="text-align:left;">
Morris County
</td>
<td style="text-align:right;">
983
</td>
<td style="text-align:right;">
448845
</td>
<td style="text-align:right;">
456.6073
</td>
<td style="text-align:right;">
43000
</td>
<td style="text-align:right;">
0.9125741
</td>
</tr>
<tr>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
1261
</td>
<td style="text-align:right;">
604996
</td>
<td style="text-align:right;">
479.7748
</td>
<td style="text-align:right;">
2190
</td>
<td style="text-align:right;">
0.9963932
</td>
</tr>
<tr>
<td style="text-align:left;">
Passaic County
</td>
<td style="text-align:right;">
1101
</td>
<td style="text-align:right;">
501826
</td>
<td style="text-align:right;">
455.7911
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
<tr>
<td style="text-align:left;">
Salem County
</td>
<td style="text-align:right;">
106
</td>
<td style="text-align:right;">
35971
</td>
<td style="text-align:right;">
339.3491
</td>
<td style="text-align:right;">
26414
</td>
<td style="text-align:right;">
0.5765969
</td>
</tr>
<tr>
<td style="text-align:left;">
Somerset County
</td>
<td style="text-align:right;">
626
</td>
<td style="text-align:right;">
320092
</td>
<td style="text-align:right;">
511.3291
</td>
<td style="text-align:right;">
8842
</td>
<td style="text-align:right;">
0.9731192
</td>
</tr>
<tr>
<td style="text-align:left;">
Sussex County
</td>
<td style="text-align:right;">
222
</td>
<td style="text-align:right;">
97770
</td>
<td style="text-align:right;">
440.4054
</td>
<td style="text-align:right;">
42718
</td>
<td style="text-align:right;">
0.6959313
</td>
</tr>
<tr>
<td style="text-align:left;">
Union County
</td>
<td style="text-align:right;">
1372
</td>
<td style="text-align:right;">
542753
</td>
<td style="text-align:right;">
395.5926
</td>
<td style="text-align:right;">
13588
</td>
<td style="text-align:right;">
0.9755761
</td>
</tr>
<tr>
<td style="text-align:left;">
Warren County
</td>
<td style="text-align:right;">
148
</td>
<td style="text-align:right;">
61596
</td>
<td style="text-align:right;">
416.1892
</td>
<td style="text-align:right;">
43671
</td>
<td style="text-align:right;">
0.5851406
</td>
</tr>
</tbody>
</table>
<p>Though the outliers like Cape May and Hudson may suggest a correlation between our coverage rate and the number of residents per officer – which would in turn suggest we may be oversampling municipalities with larger police departments – the actual correlation is not significant:</p>
<pre class="r"><code># Weighted by population, there is no significant correlation between
# residents_per_officer and our coverage.
lm(resident_per_officer ~ coverage,
   officer_count_pop_by_county,
   weights = population) %&gt;%
  summary() %&gt;%
  magrittr::use_series(&quot;coefficients&quot;)</code></pre>
<pre><code>##              Estimate Std. Error     t value   Pr(&gt;|t|)
## (Intercept) 429.88826   184.1959  2.33386393 0.03073777
## coverage    -10.59814   196.2501 -0.05400322 0.95749639</code></pre>
<pre class="r"><code># Plot number of residents per officer by coverage
outliers &lt;- officer_count_pop_by_county %&gt;%
  filter(
    population == min(population) | population == max(population) |
      coverage == min(coverage) | coverage == max(coverage) |
      resident_per_officer == min(resident_per_officer) |
      resident_per_officer == max(resident_per_officer)
  )
officer_count_pop_by_county %&gt;%
  ggplot(aes(x = coverage, y = resident_per_officer)) +
  geom_point(aes(size = population)) +  
  ggrepel::geom_label_repel(data = outliers, aes(label = county)) +
  labs(
    title =
      str_wrap(
        &quot;County population vs proportion of residents with single-municipality PDs&quot;
      ),
    subtitle = &quot;2019 Population Estimates, 2021 Officer Counts&quot;,
    caption = &quot;Source: US Census, NJ OAG&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
</div>
<div id="mapping-municipalities-with-large-police-departments-relative-to-their-population" class="section level2">
<h2>Mapping municipalities with large police departments relative to their population</h2>
<p>Now that we have our data set, let’s take a look at the municipalities with the largest police departments relative to their population:</p>
<pre class="r"><code>top_fifteen &lt;- officer_count_pop %&gt;%
  mutate(residents_per_officer = population / officer_count) %&gt;%
  slice_min(n = 15, order_by = residents_per_officer) %&gt;%
  select(agency_name,
         county,
         residents_per_officer,
         officer_count,
         population)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-12">Table 4: </span>top_fifteen (largest PDs relative to population)
</caption>
<thead>
<tr>
<th style="text-align:left;">
agency_name
</th>
<th style="text-align:left;">
county
</th>
<th style="text-align:right;">
residents_per_officer
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:right;">
population
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Mantoloking Boro PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
27.66667
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
249
</td>
</tr>
<tr>
<td style="text-align:left;">
Deal PD
</td>
<td style="text-align:left;">
Monmouth County
</td>
<td style="text-align:right;">
34.23810
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
719
</td>
</tr>
<tr>
<td style="text-align:left;">
Harvey Cedars Boro PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
38.33333
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
345
</td>
</tr>
<tr>
<td style="text-align:left;">
Stone Harbor Boro PD
</td>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
47.64706
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
810
</td>
</tr>
<tr>
<td style="text-align:left;">
Allenhurst PD
</td>
<td style="text-align:left;">
Monmouth County
</td>
<td style="text-align:right;">
53.66667
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
483
</td>
</tr>
<tr>
<td style="text-align:left;">
Avalon Boro PD
</td>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
56.18182
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
1236
</td>
</tr>
<tr>
<td style="text-align:left;">
Longport PD
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
60.78571
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
851
</td>
</tr>
<tr>
<td style="text-align:left;">
Hi-Nella PD
</td>
<td style="text-align:left;">
Camden County
</td>
<td style="text-align:right;">
78.00000
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
858
</td>
</tr>
<tr>
<td style="text-align:left;">
Sea Isle City PD
</td>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
84.54167
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
2029
</td>
</tr>
<tr>
<td style="text-align:left;">
Lavallette PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
84.81818
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
1866
</td>
</tr>
<tr>
<td style="text-align:left;">
Long Beach Twp PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
87.74286
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
3071
</td>
</tr>
<tr>
<td style="text-align:left;">
Ship Bottom Boro PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
88.69231
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1153
</td>
</tr>
<tr>
<td style="text-align:left;">
Beach Haven PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
92.69231
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1205
</td>
</tr>
<tr>
<td style="text-align:left;">
Bayhead Boro PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
108.55556
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
977
</td>
</tr>
<tr>
<td style="text-align:left;">
Surf City PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
109.00000
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
1199
</td>
</tr>
</tbody>
</table>
<p>In case the names of these relatively smaller municipalities don’t mean much to you, let’s take a look at them on a map. We’ll use the <a href="https://cran.r-project.org/web/packages/tigris/index.html">tigris</a> package to get the <a href="https://r-spatial.github.io/sf/">shapefiles</a> for the municipalities from the US census:</p>
<pre class="r"><code>library(tigris)
options(tigris_use_cache = TRUE)
nj_municipality_map &lt;- counties %&gt;%
  map_df( ~ county_subdivisions(&quot;NJ&quot;, county = ., class = &quot;sf&quot;))</code></pre>
<p>Next we join the officer count data to the map and plot.</p>
<pre class="r"><code># Add the residents_per_officer to the map
officer_count_pop &lt;- officer_count_pop %&gt;%
  mutate(residents_per_officer = population / officer_count)
map_with_values &lt;-
  left_join(nj_municipality_map, officer_count_pop, by = &quot;GEOID&quot;)

# Select the top values for labeling
labels &lt;- map_with_values %&gt;%
  slice_min(n = 15, order_by = residents_per_officer) %&gt;%
  arrange(desc(INTPTLAT))

# Map the officer density
scale_breaks &lt;- c(30, 40, 60, 120)
ggplot(map_with_values) +
  geom_sf(aes(fill = residents_per_officer, geometry = geometry, size = .2 )) +
  ggrepel::geom_label_repel(
    data = labels,
    mapping = aes(label = NAME, geometry = geometry),
    stat = &quot;sf_coordinates&quot;,
    nudge_x = -.7,
    min.segment.length = 0
  ) +
  scale_size_identity() +
  scale_fill_gradient(
    na.value = &quot;lightgrey&quot;,
    low = &quot;white&quot;,
    high = &quot;red&quot;,
    trans = &quot;reciprocal&quot;,
    breaks = scale_breaks,
    name = &quot;Residents Per Officer&quot;
  ) +
  labs(
    title = str_wrap(
      &quot;NJ municipalities with large police departments relative to population&quot;
    ),
    subtitle = &quot;2019 Population Estimates, 2021 Officer Counts&quot;,
    caption = &quot;Source: US Census, NJ OAG&quot;
  ) +
  theme(
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_rect(fill = &quot;lightblue&quot;),
    panel.grid.major = element_line(color = &quot;lightblue&quot;),
    legend.position = &quot;bottom&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>So, a map of the largest percapita municipal PDs in NJ is a map of the Jersey Shore, plus Hi-Nella.</p>
</div>
<div id="part-time-residents-and-part-time-officers" class="section level2">
<h2>Part-time residents and part-time officers</h2>
<div id="hi-nella" class="section level3">
<h3>Hi-Nella</h3>
<p>Before we get to the shore towns, let’s take a quick look at the borough of Hi-Nella. A population of <code>858</code> and <code>11</code> police officers – that sure seems like a lot!</p>
<p>Back in 2010, the Star-Ledger reported on Hi-Nella (<a href="https://www.nj.com/ledgerlive/2010/12/towns_that_shouldnt_exist_part.html">Towns that Shouldn’t Exist Part 2: Borough of Hi-Nella</a>). At that time, the population was <code>1029</code> and the police department had <code>13</code> officers. But, the Star-Ledger notes, this a “mostly <em>part-time</em> police force”.</p>
<p>The NJ OAG data set does not distinguish part-time from full-time officers, so it is not clear how much of the Hi-Nella PD is part time. The <a href="https://www.hinellaboro.org/police-department">Hi-Nella PD website</a> lists a Chief, a Lieutenant and a Detective, presumably all full-time, and no other officers. Perhaps the department has three full-time and <code>8</code> part-time officers, which is still on the large side.</p>
</div>
<div id="jersey-shore-towns" class="section level3">
<h3>Jersey Shore towns</h3>
<p>The other fourteen agencies on the list are all on the Jersey Shore. The most extreme example is Mantoloking, with <code>9</code> officers and only <code>249</code> residents.</p>
<div id="mantoloking" class="section level4">
<h4>Mantoloking</h4>
<p>The <a href="https://en.wikipedia.org/wiki/Mantoloking,_New_Jersey">wikipedia page</a> for Mantoloking gives a good explanation for why this might be: during the summer months, the population swells to approximately <code>5000</code>. For a populuation of <code>5000</code>, nine officers is actually lower than the state average: more than <code>500</code> residents per officer. Indeed, the Mantoloking PD website indicates that the department <a href="https://www.mantoloking.org/police-department/pages/career-information">hires seasonal officers</a> in the summer, and that it has <a href="https://www.mantoloking.org/police-department/pages/history">nine full-time officers</a>.</p>
<p>Note the contrast with Hi-Nella – both Hi-Nella and Mantoloking employ part-time officers, but part-time officers in Hi-Nella are included in the agency size, while part-time officers in Mantoloking are excluded. It is not clear how most departments have counted their part-time officers. <a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p>Returning the the shore towns, it is clear that many of them have seasonal patterns similar to Mantoloking. For example, <a href="https://en.wikipedia.org/wiki/Deal,_New_Jersey">Deal’s</a> population increases ten-fold in the summer.</p>
</div>
</div>
</div>
<div id="isolating-the-shore-towns" class="section level2">
<h2>Isolating the shore towns</h2>
<p>The NJ map includes several landless non-municipal county subdivisions off the coast, which we can identify by filtering on <code>ALAND == 0</code>.</p>
<pre class="r"><code># Select the landless regions and plot the GEOIDs
water &lt;- nj_municipality_map %&gt;% filter(ALAND == 0)
ggplot(nj_municipality_map) +
  geom_sf(aes(geometry = geometry)) +
  geom_sf_label(data = water,
                mapping = aes(label = GEOID, geometry = geometry)) +
  labs(title = str_wrap(&quot;Landless county subdivision GEOIDs in NJ&quot;),
       caption = &quot;Source: US Census&quot;) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>We can take a stab at defining the “Jersey Shore” as those municipalities that border any of these regions, excluding the Delaware Bay region <code>3401100000</code>.</p>
<pre class="r"><code># Build the jersey shore map
jersey_shore_water &lt;- water %&gt;% filter(GEOID != &quot;3401100000&quot;)
jersey_shore_indices &lt;-
  sf::st_intersects(jersey_shore_water, nj_municipality_map) %&gt;%
  unlist() %&gt;% unique()
jersey_shore &lt;-
  nj_municipality_map[jersey_shore_indices, ] %&gt;% setdiff(water)

# Plot the jersey_shore towns
ggplot(jersey_shore) + geom_sf() +
  ggrepel::geom_label_repel(
    mapping = aes(label = NAME, geometry = geometry),
    stat = &quot;sf_coordinates&quot;,
    nudge_x = -.7,
    min.segment.length = 0,
    size = 3
  ) +
  labs(title = str_wrap(&quot;52 \&quot;Jersey Shore\&quot; municipalities&quot;),
       caption = &quot;Source: US Census&quot;) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-16-1.png" width="672" />
Now we can add a flag, <code>shore_town</code>, to the <code>officer_count_pop</code> table:</p>
<pre class="r"><code>officer_count_pop &lt;- officer_count_pop %&gt;% 
  mutate(shore_town=GEOID %in% jersey_shore$GEOID)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-18">Table 5: </span>head(officer_count_pop) (with shore_town flag)
</caption>
<thead>
<tr>
<th style="text-align:left;">
GEOID
</th>
<th style="text-align:left;">
agency_name
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:left;">
municipality
</th>
<th style="text-align:left;">
county
</th>
<th style="text-align:right;">
population
</th>
<th style="text-align:right;">
residents_per_officer
</th>
<th style="text-align:left;">
shore_town
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
3400100100
</td>
<td style="text-align:left;">
Absecon City PD
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:left;">
Absecon city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
8818
</td>
<td style="text-align:right;">
304.0690
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:left;">
3400102080
</td>
<td style="text-align:left;">
Atlantic City PD
</td>
<td style="text-align:right;">
257
</td>
<td style="text-align:left;">
Atlantic City city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
37743
</td>
<td style="text-align:right;">
146.8599
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:left;">
3400107810
</td>
<td style="text-align:left;">
Brigantine PD
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:left;">
Brigantine city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
8650
</td>
<td style="text-align:right;">
247.1429
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:left;">
3400120350
</td>
<td style="text-align:left;">
Egg Harbor City PD
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:left;">
Egg Harbor City city
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
4052
</td>
<td style="text-align:right;">
238.3529
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:left;">
3400120290
</td>
<td style="text-align:left;">
Egg Harbor Twp PD
</td>
<td style="text-align:right;">
92
</td>
<td style="text-align:left;">
Egg Harbor township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
42249
</td>
<td style="text-align:right;">
459.2283
</td>
<td style="text-align:left;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:left;">
3400125560
</td>
<td style="text-align:left;">
Galloway Twp PD
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:left;">
Galloway township
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
35618
</td>
<td style="text-align:right;">
508.8286
</td>
<td style="text-align:left;">
TRUE
</td>
</tr>
</tbody>
</table>
</div>
<div id="comparing-the-jersey-shore-to-the-rest-of-the-state" class="section level2">
<h2>Comparing the Jersey Shore to the rest of the state</h2>
<p>As expected, the small Jersey Shore towns (like Mantoloking and Deal) have noticeably larger police forces relative to their population than the rest of the state. But this distinction starts to break down with larger shore towns:</p>
<pre class="r"><code># Plot the officer count vs the population for small and medium towns,
# separating the shore towns from the rest of the state
officer_count_pop %&gt;%
  mutate(town_size = factor(
    case_when(
      population &lt; 5000 ~ &quot;Small&quot;,
      population &lt; 50000 ~ &quot;Medium&quot;,
      TRUE ~ &quot;Large&quot;
    ),
    levels = c(&quot;Small&quot;, &quot;Medium&quot;, &quot;Large&quot;)
  )) %&gt;%
  filter(town_size != &quot;Large&quot;) %&gt;%
  ggplot(aes(x = population, y = officer_count, color = shore_town)) +
  geom_point() +
  geom_smooth(se = FALSE, method=&quot;loess&quot;) +
  facet_wrap(&quot;town_size&quot;, scales = &quot;free&quot;) +
  labs(title = &quot;NJ Residents Per Municipal Law Enforcement Officer&quot;,
       subtitle = &quot;Small and Medium Sized Towns, Jersey Shore vs Rest of State&quot;,
       caption = &quot;Source: US Census, NJ OAG&quot;) +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>If we look at just the 26 small shore towns – population at most <code>5000</code> – the number of residents per officer is <code>111</code>, compared to <code>415</code> for the rest of the state:</p>
<pre class="r"><code>shore_vs_non_shore &lt;- officer_count_pop %&gt;%
  mutate(small_shore_town = (population &lt;= 5000 &amp; shore_town)) %&gt;%
  group_by(small_shore_town) %&gt;%
  summarise(officer_count = sum(officer_count),
            population = sum(population)) %&gt;%
  mutate(res_per_officer = population / officer_count)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-21">Table 6: </span>shore_vs_non_shore
</caption>
<thead>
<tr>
<th style="text-align:left;">
small_shore_town
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:right;">
population
</th>
<th style="text-align:right;">
res_per_officer
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
FALSE
</td>
<td style="text-align:right;">
19731
</td>
<td style="text-align:right;">
8187311
</td>
<td style="text-align:right;">
414.9466
</td>
</tr>
<tr>
<td style="text-align:left;">
TRUE
</td>
<td style="text-align:right;">
468
</td>
<td style="text-align:right;">
52130
</td>
<td style="text-align:right;">
111.3889
</td>
</tr>
</tbody>
</table>
<p>With this in mind, let’s redo our look at the municipalities with the largest police departments relative to population after excluding the small shore towns. Our new top fifteen is:</p>
<pre class="r"><code>officer_count_pop_core &lt;- officer_count_pop %&gt;%
  filter(population &gt; 5000 | shore_town == FALSE)

top_fifteen_core &lt;- officer_count_pop_core %&gt;% 
  slice_min(n = 15, order_by = residents_per_officer) %&gt;%
  select(agency_name,
         county,
         residents_per_officer,
         officer_count,
         population)</code></pre>
<table class="kable">
<caption>
<span id="tab:unnamed-chunk-23">Table 7: </span>top_fifteen_core (largest PDs relative to population, exluding small shore towns)
</caption>
<thead>
<tr>
<th style="text-align:left;">
agency_name
</th>
<th style="text-align:left;">
county
</th>
<th style="text-align:right;">
residents_per_officer
</th>
<th style="text-align:right;">
officer_count
</th>
<th style="text-align:right;">
population
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Hi-Nella PD
</td>
<td style="text-align:left;">
Camden County
</td>
<td style="text-align:right;">
78.0000
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
858
</td>
</tr>
<tr>
<td style="text-align:left;">
Far Hills PD
</td>
<td style="text-align:left;">
Somerset County
</td>
<td style="text-align:right;">
112.8750
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
903
</td>
</tr>
<tr>
<td style="text-align:left;">
Lower Alloways Creek Twp PD
</td>
<td style="text-align:left;">
Salem County
</td>
<td style="text-align:right;">
119.4286
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1672
</td>
</tr>
<tr>
<td style="text-align:left;">
South Hackensack PD
</td>
<td style="text-align:left;">
Bergen County
</td>
<td style="text-align:right;">
121.7500
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
2435
</td>
</tr>
<tr>
<td style="text-align:left;">
Moonachie PD
</td>
<td style="text-align:left;">
Bergen County
</td>
<td style="text-align:right;">
128.6667
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
2702
</td>
</tr>
<tr>
<td style="text-align:left;">
Chesilhurst PD
</td>
<td style="text-align:left;">
Camden County
</td>
<td style="text-align:right;">
134.8333
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1618
</td>
</tr>
<tr>
<td style="text-align:left;">
West Wildwood Boro PD
</td>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
137.5000
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
550
</td>
</tr>
<tr>
<td style="text-align:left;">
Fairfield PD
</td>
<td style="text-align:left;">
Essex County
</td>
<td style="text-align:right;">
143.7308
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:right;">
7474
</td>
</tr>
<tr>
<td style="text-align:left;">
Atlantic City PD
</td>
<td style="text-align:left;">
Atlantic County
</td>
<td style="text-align:right;">
146.8599
</td>
<td style="text-align:right;">
257
</td>
<td style="text-align:right;">
37743
</td>
</tr>
<tr>
<td style="text-align:left;">
Pemberton Boro PD
</td>
<td style="text-align:left;">
Burlington County
</td>
<td style="text-align:right;">
147.1111
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1324
</td>
</tr>
<tr>
<td style="text-align:left;">
Alpine PD
</td>
<td style="text-align:left;">
Bergen County
</td>
<td style="text-align:right;">
153.6667
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1844
</td>
</tr>
<tr>
<td style="text-align:left;">
Essex Fells PD
</td>
<td style="text-align:left;">
Essex County
</td>
<td style="text-align:right;">
160.6154
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
2088
</td>
</tr>
<tr>
<td style="text-align:left;">
Ocean City PD
</td>
<td style="text-align:left;">
Cape May County
</td>
<td style="text-align:right;">
161.3382
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
10971
</td>
</tr>
<tr>
<td style="text-align:left;">
Winfield PD
</td>
<td style="text-align:left;">
Union County
</td>
<td style="text-align:right;">
167.0000
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1503
</td>
</tr>
<tr>
<td style="text-align:left;">
Oceangate Boro PD
</td>
<td style="text-align:left;">
Ocean County
</td>
<td style="text-align:right;">
169.5833
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
2035
</td>
</tr>
</tbody>
</table>
<p>Hi-Nella is the new leader, followed by Far Hills and Lower Alloways Creek. It is not clear if either Far Hills or Lower Alloways Creek is including part-time officers, like Hi-Nella does. The size of the Lower Alloways Creek PD may be related to the presence of the nuclear power plant. West Wildwood and Ocean Gate should probably be considered part of the Jersey Shore, though they don’t actually border the ocean.</p>
<p>Geographically, no clear pattern appears, except perhaps that South Jersey is somewhat over-represented:</p>
<pre class="r"><code># Add the residents_per_officer to the map, excluding shore towns
map_with_values &lt;-
  left_join(nj_municipality_map, officer_count_pop_core, by = &quot;GEOID&quot;)

# Map the officer density
labels &lt;- map_with_values %&gt;%
  slice_min(n = 15, order_by = residents_per_officer) %&gt;%
  arrange(desc(INTPTLAT))

# Plot the map
scale_breaks &lt;- c(90, 120, 180, 360)
ggplot(map_with_values) +
  geom_sf(aes(fill = residents_per_officer, geometry = geometry, size = .2 )) +
  ggrepel::geom_label_repel(
    data = labels,
    mapping = aes(label = NAME, geometry = geometry),
    stat = &quot;sf_coordinates&quot;,
    nudge_x = -.7,
    min.segment.length = 0
  ) +
  scale_size_identity() +
  scale_fill_gradient(
    na.value = &quot;lightgrey&quot;,
    low = &quot;white&quot;,
    high = &quot;red&quot;,
    trans = &quot;reciprocal&quot;,
    breaks = scale_breaks,
    name = &quot;Residents Per Officer&quot;
  ) +
  labs(
    title = str_wrap(
      &quot;NJ municipalities with large police departments relative to population, small shore towns excluded&quot;
    ),
    subtitle = &quot;2019 Population Estimates, 2021 Officer Counts&quot;,
    caption = &quot;Source: US Census, NJ OAG&quot;
  ) +
  theme(
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.background = element_rect(fill = &quot;lightblue&quot;),
    panel.grid.major = element_line(color = &quot;lightblue&quot;),
    legend.position = &quot;bottom&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="next" class="section level2">
<h2>Next</h2>
<p>In subsequent posts, we dig in further, looking at:</p>
<ul>
<li>Municipality demographics (US Census)</li>
<li>Department diversity (<code>njoagleod</code> package)</li>
<li>Use of force (<code>njoaguof</code> package)</li>
</ul>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>The municipal PD officer counts are also available in the <a href="https://ucr.fbi.gov/crime-in-the-u.s/2018/crime-in-the-u.s.-2018/tables/table-78/table-78-state-cuts/new-jersey.xls">FBI Uniform Crime Reports</a>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Note that the tidycensus package needs to be supplied with a census API key, which is not shown in the code snippet. See <a href="https://walker-data.com/tidycensus/articles/basic-usage.html">here</a>.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>The FBI UCF claims that the numbers are for “Full-time Law Enforcement Employees”, and lists 13 as the size of the Hi-Nella PD in 2018. Since Hi-Nella is evidently improperly including part-time officers its report to the FBI, we suspect that the inclusion of part-time officers in the NJ OAG report is also an error, and that most municipalities in the NJ OAG Law Enforcement Officer Diversity data set are including only full-time officers.
According to the <a href="https://www.njoag.gov/policerecruiting/">NJ OAG</a>, all officers in the dataset are full-time.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
